-- IP-2 — Product variants. Adds the ProductVariant table, OrderItem
-- variant FK + snapshots, a backfill of one "Default" variant per
-- existing Product, and a tsvector-trigger update so variant names
-- (e.g. "500 ml") feed product search the same way names + aliases do.
--
-- Spurious `DROP INDEX` lines for the PostGIS + pg_trgm indexes
-- (Store_location_gist_idx, Product_searchAliases_gin_idx,
-- Product_searchVector_gin_idx) generated by Prisma have been stripped
-- per the documented gotcha — those indexes live outside the Prisma
-- schema model.
--
-- The backfill leaves owner-visible Defaults named "Default" with
-- unitValue=1 as a placeholder; owners rename per IP-2.0 UX.

-- ===========================================================
-- 1. Schema additions
-- ===========================================================

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN     "variantId" TEXT,
ADD COLUMN     "variantNameSnapshot" TEXT,
ADD COLUMN     "variantUnitValueSnapshot" DECIMAL(10,2);

-- CreateTable
CREATE TABLE "ProductVariant" (
    "id" TEXT NOT NULL,
    "productId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "unitValue" DECIMAL(10,2) NOT NULL,
    "unit" "Unit" NOT NULL,
    "pricePaise" INTEGER NOT NULL,
    "isAvailable" BOOLEAN NOT NULL DEFAULT true,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "sku" TEXT,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "imageUrl" TEXT,
    "imagePublicId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProductVariant_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ProductVariant_productId_isAvailable_idx" ON "ProductVariant"("productId", "isAvailable");

-- CreateIndex
CREATE INDEX "ProductVariant_sku_idx" ON "ProductVariant"("sku");

-- CreateIndex
CREATE UNIQUE INDEX "ProductVariant_productId_name_key" ON "ProductVariant"("productId", "name");

-- AddForeignKey
ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_variantId_fkey" FOREIGN KEY ("variantId") REFERENCES "ProductVariant"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ===========================================================
-- 2. Search trigger update — variant names join the tsvector.
--
-- The product-level BEFORE INSERT/UPDATE trigger now aggregates every
-- variant.name for its row at weight B (between name+aliases at A and
-- the secondary fields at C). A new AFTER trigger on ProductVariant
-- touches the parent Product on insert/rename/delete so its trigger
-- re-fires and the vector stays current. The "touch" is a no-op write
-- on `searchAliases` because that column is in the watched-set of the
-- Product trigger's UPDATE OF clause.
-- ===========================================================

CREATE OR REPLACE FUNCTION product_search_vector_update()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  subcat_name  text;
  cat_name     text;
  dept_name    text;
  store_name   text;
  variant_names text;
BEGIN
  SELECT s.name, c.name, d.name
    INTO subcat_name, cat_name, dept_name
    FROM "Subcategory" s
    JOIN "Category"   c ON c.id = s."categoryId"
    JOIN "Department" d ON d.id = c."departmentId"
   WHERE s.id = NEW."subcategoryId";

  SELECT name INTO store_name FROM "Store" WHERE id = NEW."storeId";

  -- IP-2: aggregate variant names so a search for "500ml" hits a product
  -- whose only "500ml" token lives on the variant, not the product name.
  -- coalesce(NULL, '') handles brand-new products (no variants yet at
  -- BEFORE INSERT time); the variant-insert trigger below refreshes the
  -- vector once those rows land.
  SELECT coalesce(string_agg(name, ' '), '')
    INTO variant_names
    FROM "ProductVariant"
    WHERE "productId" = NEW.id;

  NEW."searchVector" :=
       setweight(to_tsvector('simple', immutable_unaccent(coalesce(NEW.name, ''))), 'A')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(array_to_string(NEW."searchAliases", ' '), ''))), 'A')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(variant_names, ''))), 'B')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(NEW.description, ''))), 'B')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(subcat_name, ''))), 'C')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(cat_name,    ''))), 'C')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(dept_name,   ''))), 'C')
    || setweight(to_tsvector('simple', immutable_unaccent(coalesce(store_name,  ''))), 'C');

  RETURN NEW;
END;
$$;

-- Variant-side propagator: on any insert / rename / delete, touch the
-- parent product so the Product BEFORE UPDATE trigger re-fires and the
-- searchVector picks up the new variant set.
CREATE OR REPLACE FUNCTION variant_propagate_search()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  target_product_id text;
BEGIN
  IF TG_OP = 'DELETE' THEN
    target_product_id := OLD."productId";
  ELSE
    target_product_id := NEW."productId";
  END IF;

  -- UPDATE fast path: only repropagate when the visible-to-search bits
  -- changed. Stock toggles + price changes don't affect the vector.
  IF TG_OP = 'UPDATE' THEN
    IF NEW.name IS NOT DISTINCT FROM OLD.name
       AND NEW."productId" IS NOT DISTINCT FROM OLD."productId" THEN
      RETURN NEW;
    END IF;
  END IF;

  -- No-op write on a column inside the Product trigger's UPDATE OF set
  -- forces the BEFORE UPDATE trigger to re-fire and recompute the vector.
  UPDATE "Product"
     SET "searchAliases" = "searchAliases"
   WHERE id = target_product_id;

  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS variant_search_propagation_trg ON "ProductVariant";
CREATE TRIGGER variant_search_propagation_trg
  AFTER INSERT OR UPDATE OR DELETE
  ON "ProductVariant"
  FOR EACH ROW
  EXECUTE FUNCTION variant_propagate_search();

-- ===========================================================
-- 3. Backfill — one "Default" variant per existing product.
--
-- unitValue=1 is a placeholder; the owner edits it from the variant
-- editor. The id pattern 'cvar_'+productId guarantees uniqueness +
-- idempotence (re-running the migration against a snapshot produces
-- the same ids).
-- ===========================================================

INSERT INTO "ProductVariant" (
  "id", "productId", "name", "unitValue", "unit",
  "pricePaise", "isAvailable", "isDefault", "sortOrder",
  "createdAt", "updatedAt"
)
SELECT
  'cvar_' || p.id,
  p.id,
  'Default',
  1,
  p.unit,
  p."pricePaise",
  p."isAvailable",
  true,
  0,
  now(),
  now()
FROM "Product" p
WHERE NOT EXISTS (
  -- Re-run safety on a snapshot rehearsal: skip products that already
  -- have a variant. On a fresh apply this clause is always true.
  SELECT 1 FROM "ProductVariant" v WHERE v."productId" = p.id
);

-- ===========================================================
-- 4. Backfill — refresh every product's searchVector so the freshly-
--    inserted default variant name is included. The variant trigger
--    above fired for each INSERT and queued a no-op UPDATE on Product,
--    so this is technically redundant in a clean apply — but explicit
--    is safer than implicit when backfill order can vary.
-- ===========================================================

UPDATE "Product"
   SET "searchAliases" = "searchAliases";
